version: "0.0.1"
services: 
  tor_service:
      container_name: tor_service
      image: "hikonomuro/tor_service_minimal:0.0.1"
      ports:
      - "9001:9001"
      - "9050:9050"
  i2p_service:
      container_name: i2p_service
      image: "meeh/i2pd"
      ports:
      - "2827:2827"
      - "4444:4444"
      - "4447:4447"
      - "7070:7070"
      - "7650:7650"
      - "7654:7654"
      - "7656:7656"