version: "3"
services: 
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce"
    ports:
      - 9000:9000
      - 8000:8000
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer:/data"